<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cfp.Application\Cfp.Application.csproj" />
    <ProjectReference Include="..\Cfp.Domain\Cfp.Domain.csproj" />
    <PackageReference Include="Azure.Communication.Email" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>
